name = "WignerMolecule"
uuid = "a601b020-ef02-470b-8b5c-5764e2d1f630"
version = "1.0.0-DEV"
authors = ["PatXue <95881915+PatXue@users.noreply.github.com> and contributors"]

[deps]
BenchmarkTools = "6e4b80f9-dd63-53aa-95a3-0cdb28fa8baf"
Carlo = "780c37f4-4e5a-43de-9e79-65c261e525a4"
FFTW = "7a1cc6ca-52ef-59f5-83cd-3a7055c09341"
HDF5 = "f67ccb44-e63f-5c2f-98bd-6dc0ccc4ba2f"
JLD2 = "033835bb-8acc-5ee8-8aae-3f567f8a3819"
JSON = "682c06a0-de6a-54ab-a142-c8b1cf79cde6"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
PeriodicArrays = "ebeed567-01e3-4f0a-88fa-2070a64c066d"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
Revise = "295af30f-e4ad-537b-8983-00126c2a3abe"
StaticArrays = "90137ffa-7385-5640-81b9-e52037218182"

[compat]
BenchmarkTools = "1.6.0"
Carlo = "<0.2.6"
FFTW = "1.10.0"
HDF5 = "0.17.2"
JLD2 = "0.6.2"
JSON = "0.21.4"
LinearAlgebra = "1.11.0, 1.10.0"
PeriodicArrays = "0.1.0"
Random = "1.11.0, 1.10.0"
Revise = "3.9.0"
StaticArrays = "1.9.15"
julia = "1.6.7"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
