[deps]
CairoMakie = "13f3f980-e62b-5c42-98c6-ff1f3baf88f0"
Carlo = "780c37f4-4e5a-43de-9e79-65c261e525a4"
CarloAnalysis = "074ae576-0ee5-4533-b44a-9466da945657"
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
GLMakie = "e9467ef8-e4e7-5192-8a1a-b1aee30e663a"
HDF5 = "f67ccb44-e63f-5c2f-98bd-6dc0ccc4ba2f"
JLD2 = "033835bb-8acc-5ee8-8aae-3f567f8a3819"
PeriodicArrays = "ebeed567-01e3-4f0a-88fa-2070a64c066d"
StaticArrays = "90137ffa-7385-5640-81b9-e52037218182"
